services:
  web:
    image: nginx:1.25-alpine
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "debug,coverage"

    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
  db:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '${DB_NAME:-app}'
      MYSQL_USER: '${DB_USER:-app}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
