services:
  web:
    image: nginx:1.25-alpine
    ports:
      - "5000:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
      - ./tasks/.taskrc:/home/www-data/.taskrc
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "debug"

    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
